export const uiText = {
  app: {
    brand: 'HECTO 근태관리',
    adminBrand: 'HECTO Q&M',
    version: 'v2.1.0',
  },
  sidebar: {
    dashboard: '대시보드',
    tracker: '상세 근무트래커',
    monthly: '월간 근태보고',
    employees: '직원 일정관리',
    employeeAdmin: '직원 관리',
    manualApproval: '수동 기록 결재',
    userRegister: '아이디 등록',
    capsUpload: '캡스 업로드',
    icalSubscriptions: '비공개 iCal 구독',
    leaves: '연차 현황',
    overtime: '초과 근무 관리',
    logout: '로그아웃',
    mypage: '마이페이지',
    adminBadge: 'ADMIN',
    leaderBadge: 'LEADER',
    attendanceRecords: '출입기록 조회 및 조정',
  },
  page: {
    dashboard: {
      title: '대시보드 모니터링',
      subtitle: '오늘 현재 출근 및 부서별 현황을 한눈에 확인합니다.',
      searchPlaceholder: '이름/사번/부서 검색',
      demoMode: '데모 모드',
      deptLabel: '부서 선택',
      allDept: '전체 부서',
      refreshTooltip: '새로고침',
      lightModeTooltip: '라이트 모드',
      darkModeTooltip: '다크 모드',
      totalLabel: '전체 직원',
      presentLabel: '정상 근무',
      lateLabel: '지각 발생',
      leaveLabel: '연차/외근',
      totalDesc: '등록된 전체 직원 수',
      presentDesc: '정상 출근 중인 직원 수',
      lateDesc: '오늘 출근 기준 시각 초과 지각자',
      leaveDesc: '반차/반반차/경조/외근 포함 처리 인원',
      statusLabels: {
        working: '근무중',
        absent: '미출근',
      },
      realtimeTitle: '실시간 직원 상태 목록',
      realtimeSub: '오늘 기준 전체 직원의 상태 및 출퇴근 기록',
      deptTitle: '부서별 출근 현황',
      deptSub: '부서별 현재 출근 비율과 출근자 현황을 보여줍니다.',
      tableHeaders: {
        employeeInfo: '사원 정보',
        dept: '부서',
        scheduledIn: '기준 출근',
        actualIn: '실제 출근',
        actualOut: '실제 퇴근',
        status: '현재 상태',
      },
    },
    monthly: {
      title: '월간 근태보고',
      subtitle: '선택된 부서의 월간 근태 및 출퇴근 상세 데이터를 집계합니다.',
      monthLabel: '월 선택',
      loading: '월간 데이터를 불러오는 중입니다...',
      tableTitle: '월간 근태 상세 현황',
      tableSub: '선택된 부서의 모든 직원 출근/퇴근 로그를 확인합니다.',
      noData: '검색 조건에 맞는 직원이 없습니다.',
      overrideBadge: '예외적용',
    },
    tracker: {
      title: '개인 상세 근무트래커',
      subtitle: '개인별 단위 상세 출근, 퇴근, 근무시간 추이를 조회하고 관리합니다.',
      myPortalTitle: '오늘 출퇴근 기록',
      myPortalSubtitle: '모바일과 간편하게 출퇴근을 기록하고 근태를 확인합니다.',
      checkinValue: '출근',
      checkoutValue: '퇴근',
      noteLabel: '비고 및 메모 입력',
      checkinDone: '출근 완료 처리',
      checkoutDone: '퇴근 완료 처리',
      todayProcess: '오늘 상태 처리',
      todaySummaryTitle: '오늘 근태 처리',
      todaySummarySub: '오늘 수집된 실시간 출퇴근 기록 현황',
      noTodayLogs: '오늘 수집된 로그가 아직 없습니다.',
      gateLabel: '기록지',
      personalSummaryTitle: '개인별 근무일정 상세 트래커',
      personalSummarySub: '주차별 출퇴근 시각, 실제 근무시간 및 초과근무 분석',
      employeeLabel: '직원',
      employeeSearchPlaceholder: '이름 검색...',
      selectedMonthLabel: '선택 월',
      viewingEmployeeLabel: '조회 직원',
      baseScheduleLabel: '기준 출근시간',
      correctionWorkDateLabel: '수정 적용 날짜',
      correctionOutTimeLabel: '퇴근 시각 (수정)',
      correctionReasonLabel: '사유',
      correctionTooltip: '원래 퇴근: {original} (사유: {reason})',
      correctionReasonFallback: '미기재',
      checkinMemoPlaceholder: '예: 외근, 출장, 회의 등 입력',
      correctionMemoPlaceholder: '예: 중간 외출 복귀, 퇴근 시간 수정',
      lateMarker: '(지각)',
      correctionSuccess: '퇴근 시각이 성공적으로 변경되었습니다.',
      correctionFailed: '퇴근 시각 변경에 실패했습니다.',
      correctionSubmit: '변경 반영',
      correctionCancel: '취소',
      loading: '근무 현황 데이터를 불러오는 중입니다...',
      noEmployeeSelected: '검색창에서 직원을 선택해 주세요.',
      workDaysLabel: '출근 일수',
      latenessLabel: '지각일수',
      holidayWorkLabel: '휴일근무 합계(주간근무)',
      hoursLabel: '시간',
      inLabel: '출근',
      outLabel: '퇴근',
      editLabel: '수정',
      workLabel: '근무',
      overtimeLabel: '초과',
      timeUnit: '시간',
      overrideBadgePrefix: '예외',
      weekdays: ['일', '월', '화', '수', '목', '금', '토'],
      lateTag: '지각',
      leaveUnit: '일',
      hourUnit: '시간',
      monthDayUnit: '일',
    },
    employees: {
      title: '직원 근무일정 및 예외 관리',
      subtitle: '직원별 기본 근무시간 등록 및 개별 날짜 예외를 관리합니다.',
      scheduleCardTitle: '직원 기본 근무일정 목록',
      scheduleCardSubtitle: '직원별 고정 근무시간과 일자별 예외를 함께 관리합니다.',
      scheduleTableHeaders: {
        info: '직원 정보',
        dept: '부서',
        base: '현재 기준 출근시간',
        change: '출근 시간 변경',
        action: '작업',
      },
      defaultTag: '기본',
      overrideAction: '예외 조정',
      adjustTitle: '직원별 예외 근무 조정',
      adjustDateLabel: '적용 날짜',
      adjustTimeLabel: '출근 기준 시간',
      adjustNoteLabel: '사유 / 메모',
      adjustPlaceholder: '예: 정기 점검 출근, 내일 야간조 출근',
      adjustSubmit: '예외 조정 적용',
      adjustCancel: '취소',
      save: '저장',
    },
    employeeAdmin: {
      title: '직원 정보 수정 및 비밀번호 초기화',
      subtitle: '직원 기본 정보를 수정하고 계정 초기 비밀번호를 관리자 권한으로 관리합니다.',
      searchPlaceholder: '이름, 사번, 부서 검색',
      refreshLabel: '새로고침',
      tableHeaders: {
        name: '이름 / 사번',
        dept: '부서',
        rank: '직급',
        position: '직책',
        admin: '관리자',
        password: '초기 비밀번호',
        action: '작업',
      },
      passwordPlaceholder: '초기 비밀번호',
      loading: '직원 정보를 불러오는 중...',
      noResult: '검색 결과가 없습니다.',
      accountRegistered: '계정 등록됨',
      accountMissing: '계정 없음',
      saving: '저장 중...',
      save: '정보 저장',
      resetting: '초기화 중...',
      reset: '비밀번호 초기화',
      resetTitle: '초기 비밀번호 재설정',
      resetAria: '초기 비밀번호 재설정',
    },
    myPortal: {
      title: '내 근태 상태 및 일정',
      subtitle: '본인 출퇴근 기록과 근무 현황을 모니터링합니다.',
    },
    myPage: {
      title: '마이페이지',
      subtitle: '사번, 이름, 로그인 아이디는 여기서 확인하고 수정할 수 있습니다.',
      infoTitle: '내 정보',
      infoSubtitle: '사번, 이름, 로그인 아이디는 여기서 확인할 수 있습니다. 부서와 직급은 지정된 곳만 수정 가능합니다.',
      profileBadge: '프로필',
      passwordBadge: '비밀번호',
      reloadTooltip: '새로고침',
      lightModeTooltip: '라이트 모드',
      darkModeTooltip: '다크 모드',
      loading: '프로필 정보를 불러오는 중...',
      loadFail: '마이페이지 정보를 불러오지 못했습니다.',
      nameLabel: '이름',
      empNoLabel: '사원번호',
      loginIdLabel: '로그인 아이디',
      deptLabel: '부서',
      rankLabel: '직급',
      selectPrompt: '선택하세요',
      saveProfile: '프로필 정보 저장',
      saveSuccess: '프로필이 저장되었습니다.',
      saveFail: '프로필 저장에 실패했습니다.',
      saveError: '프로필 저장에 실패했습니다.',
      passwordTitle: '비밀번호 변경',
      passwordSubtitle: '새 비밀번호를 입력하면 즉시 반영됩니다.',
      newPasswordLabel: '새 비밀번호',
      confirmPasswordLabel: '새 비밀번호 확인',
      newPasswordPlaceholder: '8자 이상',
      confirmPasswordPlaceholder: '다시 입력',
      passwordSave: '비밀번호 변경',
      shortPasswordError: '비밀번호는 8자 이상이어야 합니다.',
      mismatchError: '비밀번호와 확인 비밀번호가 일치하지 않습니다.',
      passwordSuccess: '비밀번호가 변경되었습니다.',
      passwordFail: '비밀번호 변경에 실패했습니다.',
      passwordError: '비밀번호 변경에 실패했습니다.',
      adminProfileName: '최고관리자',
      employeeProfileName: '직원',
    },
    leaves: {
      title: '연차 현황',
      subtitle: '직원들의 연차 및 휴가 사용 현황을 확인합니다.',
      eyebrow: '연차 현황',
      monthLabel: '월 선택',
      tableTitle: '전사 연차 현황',
      tableSub: '직원들의 연차 및 반차 사용 현황을 확인하는 연차 이력 리스트입니다.',
      tableHeaders: {
        empNo: '사원번호',
        name: '사원명',
        type: '연차 종류',
        start: '연차 시작일',
        end: '연차 종료일',
        days: '사용 일수',
      },
      empty: '현재 선택된 월에 해당하는 연차 기록이 없습니다.',
    },
    overtime: {
      title: '초과근무 관리',
      subtitle: '외부사업 부서의 초과시간을 기간별로 집계하고 남은 조정 가능 시간을 확인합니다.',
      formTitle: '정산 기간 등록',
      formSubtitle: '초과근무 집계 구간을 먼저 등록한 뒤, 기간별 요약을 확인합니다.',
      periodLabel: '기준 기간',
      nameLabel: '기간명',
      startLabel: '시작일',
      endLabel: '종료일',
      memoLabel: '설명 / 비고',
      register: '등록',
      overviewTitle: '기간별 초과근무 요약',
      overviewSubtitle: '각 기간의 평균 근무시간과 남은 조정 가능 시간을 보여줍니다.',
      detailTitle: '선택 기간 대상자별 상세',
      detailSubtitle: '외부사업 부서만 집계되며, 초과시간은 30분 단위로 0.5시간씩 계산합니다.',
      externalDeptNotice: '대상 부서는 사업개발팀, 사업관리 1팀, 사업관리 2팀, 사업관리 3팀만 포함됩니다.',
      overviewHeaders: {
        round: '차수',
        name: '이름',
        period: '기간',
        average: '평균',
        remaining: '잔여 조정',
        manage: '관리',
      },
      detailHeaders: {
        empNo: '사원번호',
        name: '이름',
        dept: '부서',
        workDays: '근무일수',
        average: '평균',
        overtime: '누적 초과시간',
      },
      noPeriod: '등록된 초과근무 기간이 없습니다.',
      noSummary: '집계 가능한 초과근무 데이터가 없습니다.',
      noDetail: '선택된 기간의 대상자 데이터가 없습니다.',
      namePlaceholder: '예: 2026년 2분기 초과정산',
      memoPlaceholder: '분기별 정산 대상 또는 정산 반영 내용',
      roundLabel: '차수',
      averageUnit: '시간',
      remainingUnit: '시간',
      stepRule: '30분 단위로 초과시간을 0.5시간으로 계산합니다.',
    },
    manualApproval: {
      title: '수동 기록 결재',
      subtitle: '직원이 수동으로 요청한 출퇴근 기록을 검토하고 결재합니다.',
      tableHeaders: {
        name: '사원명',
        type: '기록 구분',
        time: '기록 시각',
        date: '대상 날짜',
        reason: '사유',
        status: '결재 상태',
        action: '결재',
      },
      empty: '수동 출퇴근 결재 요청 이력이 없습니다.',
      approve: '승인',
      reject: '반려',
      approved: '승인완료',
      rejected: '반려됨',
      pending: '대기중',
    },
    userRegister: {
      title: '신규 사용자 계정 등록',
      subtitle: '시스템 로그인을 위한 아이디와 사원번호 정보를 함께 등록합니다.',
      empNoLabel: '사원번호',
      nameLabel: '이름',
      loginIdLabel: '로그인 아이디',
      passwordLabel: '초기 비밀번호',
      rankLabel: '직급 (선택)',
      positionLabel: '직책 (선택 - 관리자 입력 시 선택)',
      teamLabel: '팀 (선택)',
      adminCheckbox: '이 계정을 시스템 관리자 권한으로 등록합니다.',
      submitLoading: '사용자 등록 중...',
      submit: '신규 사용자 등록',
      sampleEmpNo: '예: 20260001',
      sampleLoginId: '예: user01 또는 사번',
      samplePassword: '8자 이상으로 입력',
      teamSearchPlaceholder: '팀 입력 후 검색',
      namePlaceholder: '홍길동',
      selectPrompt: '선택하세요',
    },
    capsUpload: {
      title: '캡스 출입기록 업로드',
      subtitle: '외부 출입기록 캡스 파일을 업로드해 빠르게 반영합니다.',
      fileLabel: '업로드할 파일',
      supportLabel: '지원 형식',
      guideTitle: '반영 방식',
      guideLines: [
        '1. 업로드한 파일에서 이름과 시간을 읽어옵니다.',
        '2. 기존 sa_attendance의 sabun + a_time 기준으로 중복은 제외됩니다.',
        '3. 반영된 기록은 월간 보고서와 대시보드에서 바로 조회됩니다.',
      ],
      successFallback: '업로드가 완료되었습니다.',
      summaryLabel: '총합',
      uploadLoading: '업로드 반영 중...',
      uploadButton: '캡스 기록 업로드',
      fileSupportHint: '.xls, .xlsx, .csv, .tsv',
      columnHint: ['사번', '발생시각', 'a_time', 'card_no', 'flag1'],
    },
    calendar: {
      eyebrow: '부서 연차 달력',
      monthSuffix: '캘린더',
      prev: '이전 달',
      next: '다음 달',
      weekdays: ['일', '월', '화', '수', '목', '금', '토'],
      noLeaves: '해당 월에 등록된 연차 기록이 없습니다.',
      holidayPrefix: '공휴일',
      leaveLegend: {
        annual: '연차',
        amHalf: '오전반차',
        pmHalf: '오후반차',
        other: '기타연차',
      },
      leaveGroupLabels: {
        annual: '연차 / 공휴일',
        halfDay: '오전반차 / 오후반차',
        halfHalf: '오전반반차 / 오후반반차',
        special: '경조연차 / 기타연차',
      },
    },
  },
  scheduleCalendar: {
    eyebrow: '일자별 근무시간 조정',
    monthSuffix: '캘린더',
    prev: '이전 달',
    next: '다음 달',
    legendBaseSchedule: '기본',
    legendOverride: '예외 적용',
    legendToday: '오늘',
    selectedEmployeeFallback: '직원 미선택',
    noDateSelected: '날짜를 선택하세요',
    departmentLabel: '부서 선택',
    employeeLabel: '직원 선택',
    noEmployees: '선택 가능한 직원이 없습니다.',
    todayTag: '오늘',
    overrideTag: '예외 적용',
    baseTag: '기본',
    checkinLabel: '출근',
    checkoutLabel: '퇴근',
    clickToAdjust: '클릭해서 조정',
    selectedEmployeeTitle: '선택 직원',
    deptSummaryLabel: '부서',
    baseScheduleSummaryLabel: '기준 출근시간',
    selectedDateSummaryLabel: '선택 날짜',
    selectedOverridesTitle: '등록된 예외 목록',
    noOverrides: '등록된 예외가 없습니다.',
    delete: '삭제',
    adjustTitle: '직원별 일자 조정',
    adjustDateLabel: '적용 날짜',
    adjustStartLabel: '출근 시간',
    adjustNoteLabel: '사유 / 메모',
    adjustNotePlaceholder: '예: 외근, 야간 전환, 일정 변경',
    noTargetMessage: '직원을 먼저 선택해 주세요.',
    cancelSelection: '선택 취소',
    applyAdjustment: '적용',
    adjustRequiredMessage: '먼저 날짜를 선택해 주세요.',
  },
  scheduleBatch: {
    title: '직원 일일 스케줄 일괄 등록',
    subtitle: '선택한 직원의 날짜를 여러 개 선택해서 한 번에 스케줄을 저장합니다.',
    modeBadgeOn: '다중 선택 모드',
    modeBadgeOff: '일반 모드',
    switchToNormal: '일반 모드 전환',
    switchToBatch: '다중 선택 모드 전환',
    targetDeptLabel: '대상 부서',
    targetDeptPlaceholder: '부서를 선택하세요',
    targetDeptSubLabel: '선택된 직원 부서',
    patternLabel: '패턴',
    selectedCountLabel: '선택 일자 수',
    memoLabel: '메모',
    memoPlaceholder: '예: 야간 운영 스케줄',
    weeklyStartLabel: '출근 기준 시각',
    weeklyEndLabel: '퇴근 기준 시각',
    selectedDatesLabel: '선택한 날짜',
    selectedDatesHelp: '캘린더에서 날짜를 클릭하거나 드래그해서 선택하세요.',
    selectedDatesEmpty: '선택된 날짜가 없습니다.',
    clearSelection: '선택 초기화',
    submit: '스케줄 일괄 등록',
    saving: '저장 중...',
    invalidDates: '선택된 날짜가 없습니다.',
    invalidEmployee: '먼저 직원을 선택해 주세요.',
    invalidPattern: '스케줄 패턴을 선택해 주세요.',
    invalidTime: '출근/퇴근 시간을 입력해 주세요.',
    invalidWeeklyTime: '주간 스케줄 시간을 확인해 주세요.',
    confirmTitle: '등록 내용을 확인해 주세요',
    confirmEmployeeLabel: '직원',
    confirmDeptLabel: '부서',
    confirmPatternLabel: '패턴',
    confirmDatesLabel: '선택 날짜',
    confirmMemoLabel: '메모',
    saveSuccess: '스케줄이 저장되었습니다.',
    saveFail: '스케줄 저장에 실패했습니다.',
    saveError: '스케줄 저장 중 오류가 발생했습니다.',
    optionNight1: '야간(18:00 - 06:00)',
    optionNight2: '야간(20:00 - 08:00)',
    optionDay10: '주간 10:00 ~ 19:00',
    optionDay08: '주간 08:00 ~ 17:00',
    optionDay09: '주간 09:00 ~ 18:00',
    optionCustom: '직접 입력',
  },
  attendanceRecords: {
    title: '직원 출입기록 조회 및 조정',
    subtitle: '선택한 직원의 특정 기간 출입기록을 확인하고, 각 기록을 출근 또는 퇴근으로 조정할 수 있습니다.',
    employeeLabel: '직원 선택',
    employeePrompt: '직원을 선택해 주세요.',
    fromLabel: '시작일',
    toLabel: '종료일',
    searchPlaceholder: '이름, 사번, 부서 검색',
    loadButton: '기록 불러오기',
    loading: '출입기록을 불러오는 중...',
    employeeLoadFail: '직원 목록을 불러오지 못했습니다.',
    empty: '선택한 조건의 출입기록이 없습니다.',
    includeManualLabel: '수동기록 포함',
    logTable: {
      time: '기록 시각',
      workDate: '귀속 근무일',
      role: '귀속 역할',
      source: '출처',
      note: '메모',
      action: '작업',
    },
    roleAuto: '자동',
    roleCheckin: '출근',
    roleCheckout: '퇴근',
    roleIgnore: '무시하기',
    notePlaceholder: '메모',
    workDateRequired: '귀속일을 선택해 주세요.',
    accessDenied: '권한이 없습니다.',
    loginRequired: '로그인이 필요합니다.',
    save: '저장',
    reset: '자동복원',
    saveSuccess: '기록 귀속이 저장되었습니다.',
    saveFail: '기록 귀속 저장에 실패했습니다.',
    saveError: '기록 귀속 저장 중 오류가 발생했습니다.',
    deleteConfirm: '이 귀속 설정을 자동으로 되돌리시겠습니까?',
    summary: {
      total: '전체 기록',
      adjusted: '귀속 조정',
      checkin: '출근 지정',
      checkout: '퇴근 지정',
    },
  },
  common: {
    allDept: '전체 부서',
    searchNoResult: '검색 조건에 맞는 직원이 없습니다.',
    loading: '불러오는 중입니다...',
    noData: '데이터가 없습니다.',
    noName: '이름 없음',
    noDept: '부서 없음',
    units: {
      person: '명',
      count: '건',
      day: '일',
      time: '시간',
    },
    adminProfileName: '최고관리자',
    employeeProfileName: '직원',
    requiredAdminRegister: '사원번호, 이름, 아이디, 초기 비밀번호는 필수 입력 항목입니다.',
    adminRegisterSuccess: '계정이 성공적으로 등록되었습니다.',
    adminRegisterFail: '계정 등록에 실패했습니다.',
    adminRegisterError: '계정 등록 요청 중 오류가 발생했습니다.',
    fileSelectRequired: '업로드할 파일을 선택해 주세요.',
    capsUploadSuccess: '캡스 출입기록이 반영되었습니다.',
    capsUploadFail: '캡스 출입기록 업로드에 실패했습니다.',
    capsUploadError: '캡스 출입기록 업로드 요청 중 오류가 발생했습니다.',
    employeeInfoLoadFail: '직원 정보를 불러오지 못했습니다.',
    employeeInfoSaveFail: '직원 정보 수정에 실패했습니다.',
    employeeInfoSaveSuccess: '직원 정보가 수정되었습니다.',
    employeeInfoSaveError: '직원 정보 수정 중 오류가 발생했습니다.',
    passwordTooShort: '초기 비밀번호는 8자 이상이어야 합니다.',
    passwordResetFail: '비밀번호 초기화에 실패했습니다.',
    passwordResetSuccess: '비밀번호가 초기화되었습니다.',
    passwordResetError: '비밀번호 초기화 중 오류가 발생했습니다.',
    leaveBackfillFail: '연차 보정 요청에 실패했습니다.',
    leaveBackfillSuccess: '연차 보정 요청이 등록되었습니다.',
    leaveBackfillError: '연차 보정 요청 중 오류가 발생했습니다.',
    overrideSaveSuccess: '대상 날짜의 근무 예외가 적용되었습니다.',
    overrideSaveFail: '근무 예외 적용에 실패했습니다.',
    overrideSaveError: '근무 예외 적용 중 오류가 발생했습니다.',
    overrideDeleteConfirm: '해당 날짜의 근무 예외를 삭제하시겠습니까?',
    overrideDeleteSuccess: '근무 예외가 삭제되었습니다.',
    overrideDeleteFail: '근무 예외 삭제에 실패했습니다.',
    overrideDeleteError: '근무 예외 삭제 중 오류가 발생했습니다.',
    scheduleSaveFail: '출근 시간 변경에 실패했습니다.',
    scheduleSaveError: '출근 시간 변경 중 오류가 발생했습니다.',
    checkinProcessError: '기록 처리 중 오류가 발생했습니다.',
    correctionProcessError: '수정 처리 중 오류가 발생했습니다.',
    manualCheckSuccess: '승인 완료',
    manualCheckRejectedSuccess: '반려 완료',
    manualCheckFail: '결재 처리에 실패했습니다.',
    manualCheckError: '결재 처리 중 오류가 발생했습니다.',
    overtimePeriodDeleteConfirm: '해당 정산 기간을 삭제하시겠습니까?',
    overtimePeriodDeleteError: '정산 기간 삭제 중 오류가 발생했습니다.',
  },
  settings: {
    nightGraceLabel: '야간 출근 인정 여유시간',
    nightGraceHelp: '야간 근무의 출근 인정 시작 시각을 근무 시작 시각보다 몇 시간 앞당겨 계산할지 설정합니다.',
    nightGraceUnit: '시간',
  },
};
