{
  "AllowMultiple": false,
  "Description": "Clean up route.js and fix baseScheduleTime calculation",
  "EndLine": 634,
  "Instruction": "Remove duplicated code block and restore correct return statement in route.js",
  "ReplacementContent": "    // 5. 부서별 분포\n    const deptDistribution = {};\n    employeeStatuses.forEach(emp => {\n      if (!deptDistribution[emp.dept]) {\n        deptDistribution[emp.dept] = { total: 0, present: 0, late: 0 };\n      }\n      deptDistribution[emp.dept].total++;\n      if (emp.status !== '미출근' && emp.status !== '연차') {\n        deptDistribution[emp.dept].present++;\n        if (emp.isLate) deptDistribution[emp.dept].late++;\n      }\n    });\n\n    const formattedDeptData = Object.keys(deptDistribution).map(dept => ({\n      name: dept,\n      total: deptDistribution[dept].total,\n      present: deptDistribution[dept].present,\n      late: deptDistribution[dept].late\n    }));\n\n    // 전체 직원 리스트 정렬본\n    const allEmployeesList = Array.from(allEmployeesMap.values()).map(emp => {\n      const todayStr = getLocalDateString(now);\n      const baseStart = getDefaultSchedule(emp.empNo);\n      const baseScheduleTime = normalizeTime(baseStart, '08:00');\n      const baseScheduleEndTime = inferScheduleEnd(baseStart, emp.dept);\n      const scheduleTime = resolveScheduleTimeForDate(emp.empNo, emp.dept, todayStr);\n      return { ...emp, baseScheduleTime, baseScheduleEndTime, scheduleTime };\n    }).sort((a, b) => a.name.localeCompare(b.name));\n\n    return NextResponse.json({\n      success: true,\n      isDemo,\n      error: error || null,\n      mode: 'supabase',\n      stats: {\n        totalEmployees: totalEmployeesCount,\n        present: presentCount,\n        absent: absentCount,\n        late: lateCount,\n        workingNow: workingNowCount,\n        leave: leaveCount,\n        attendanceRate: totalEmployeesCount > 0 ? Math.round((presentCount / totalEmployeesCount) * 100) : 0\n      },\n      weeklyTrend,\n      deptData: formattedDeptData,",
  "StartLine": 564,
  "TargetContent": "    // 5. 부서별 분포\n    const deptDistribution = {};\n    employeeStatuses.forEach(emp => {\n      if (!deptDistribution[emp.dept]) {\n        deptDistribution[emp.dept] = { total: 0, present: 0, late: 0 };\n      }\n      deptDistribution[emp.dept].total++;\n      if (emp.status !== '미출근' && emp.status !== '연차') {\n        deptDistribution[emp.dept].present++;\n        if (emp.isLate) deptDistribution[emp.dept].late++;\n      }\n    });\n\n    const formattedDeptData = Object.keys(deptDistribution).map(dept => ({\n      name: dept,\n      const dayEmpNos = new Set(dayLogs.map(log => log.Sabun || log.empNo));\n\n      if ((d.getDay() === 0 || d.getDay() === 6) && dayEmpNos.size === 0) continue;\n\n      weeklyTrend.push({\n        date: dStr.substring(5, 10).replace('-', '/'),\n        dayName,\n        count: dayEmpNos.size,\n        rate: totalEmployeesCount > 0 ? Math.round((dayEmpNos.size / totalEmployeesCount) * 100) : 0\n      });\n    }\n\n    // 5. 부서별 분포\n    const deptDistribution = {};\n    employeeStatuses.forEach(emp => {\n      if (!deptDistribution[emp.dept]) {\n        deptDistribution[emp.dept] = { total: 0, present: 0, late: 0 };\n      }\n      deptDistribution[emp.dept].total++;\n      if (emp.status !== '미출근' && emp.status !== '연차') {\n        deptDistribution[emp.dept].present++;\n        if (emp.isLate) deptDistribution[emp.dept].late++;\n      }\n    });\n\n    const formattedDeptData = Object.keys(deptDistribution).map(dept => ({\n      name: dept,\n      total: deptDistribution[dept].total,\n      present: deptDistribution[dept].present,\n      late: deptDistribution[dept].late\n    }));\n\n    // 전체 직원 리스트 정렬본\n    const allEmployeesList = Array.from(allEmployeesMap.values()).map(emp => {\n      const todayStr = getLocalDateString(now);\n      const baseStart = getDefaultSchedule(emp.empNo);\n      const baseScheduleTime = normalizeTime(baseStart, '08:00');\n      const baseScheduleEndTime = inferScheduleEnd(baseStart, emp.dept);\n      const scheduleTime = resolveScheduleTimeForDate(emp.empNo, emp.dept, todayStr);\n      return { ...emp, baseScheduleTime, baseScheduleEndTime, scheduleTime };\n    }).sort((a, b) => a.name.localeCompare(b.name));\n      isDemo,\n      error: error || null,\n      mode: 'supabase',\n      stats: {\n        totalEmployees: totalEmployeesCount,\n        present: presentCount,\n        absent: absentCount,\n        late: lateCount,\n        workingNow: workingNowCount,\n        leave: leaveCount,\n        attendanceRate: totalEmployeesCount > 0 ? Math.round((presentCount / totalEmployeesCount) * 100) : 0\n      },\n      weeklyTrend,\n      deptData: formattedDeptData,",
  "TargetFile": "C:/Users/Owner/Documents/antigravity/agitated-raman/src/app/api/attendance/route.js",
  "toolAction": "Cleaning up route.js duplicates",
  "toolSummary": "Replace file content in route.js"
}