const fs = require('fs');

const path = 'src/components/tabs/ScheduleTab.js';
const lines = fs.readFileSync(path, 'utf8').split(/\r?\n/);

const block = [
  "        <div style={{",
  "          display: 'grid',",
  "          gridTemplateColumns: 'minmax(220px, 0.9fr) minmax(240px, 1fr) minmax(220px, 0.8fr) auto',",
  "          gap: '12px',",
  "          alignItems: 'end'",
  '        }}>',
  '          <div>',
  '            <div className="form-label">직원 검색</div>',
  "            <div style={{ position: 'relative' }}>",
  '              <Search style={{ position: \'absolute\', left: 12, top: \'50%\', transform: \'translateY(-50%)\', width: 14, height: 14, color: \'var(--text-2)\' }} />',
  '              <input',
  '                className="form-input"',
  '                value={empSearchQuery}',
  '                onChange={(e) => setEmpSearchQuery(e.target.value)}',
  '                placeholder="이름 / 사번 / 부서 검색"',
  '                style={{ paddingLeft: 34 }}',
  '              />',
  '            </div>',
  '          </div>',
  '',
  '          <div>',
  '            <div className="form-label">직원 선택</div>',
  '            <select',
  '              className="ui-select"',
  '              value={selectedEmpNo}',
  '              onChange={(e) => {',
  '                setScheduleSelectedEmpNo(e.target.value);',
  '                setOverrideTarget(null);',
  "                setOverrideDate('');",
  '                setScheduleSelectedDates([]);',
  '                setAllowOvertime(false);',
  "                setOverrideNote('');",
  '              }}',
  "              style={{ width: '100%' }}",
  '            >',
  '              {filteredScheduleEmployees.length === 0 ? (',
  '                <option value="">선택 가능한 직원이 없습니다</option>',
  '              ) : (',
  '                filteredScheduleEmployees.map((emp) => (',
  '                  <option key={emp.empNo} value={emp.empNo}>{emp.name} ({emp.empNo}) · {emp.dept}</option>',
  '                ))',
  '              )}',
  '            </select>',
  '          </div>',
  '',
  '          <div>',
  '            <div className="form-label">기본 출근 시간</div>',
  '            <select',
  '              className="ui-select"',
  '              value={currentSchedule}',
  '              disabled={!selectedEmp}',
  '              onChange={(e) => {',
  '                if (!selectedEmp) return;',
  '                setTempSchedules((prev) => ({ ...prev, [selectedEmp.empNo]: e.target.value }));',
  '              }}',
  "              style={{ width: '100%' }}",
  '            >',
  '              {SCHEDULE_TIME_OPTIONS.map((time) => (',
  "                <option key={time} value={time}>{time}{time === '08:00' ? ' (기본)' : ''}</option>",
  '              ))}',
  '            </select>',
  '          </div>',
  '',
  '          <button',
  '            type="button"',
  '            className="login-btn"',
  '            disabled={!selectedEmp || !isScheduleChanged || isScheduleSaving}',
  '            onClick={() => selectedEmp && handleSaveSchedule(selectedEmp.empNo, currentSchedule)}',
  "            style={{ marginTop: 0, minWidth: 118, background: isScheduleChanged ? 'var(--blue)' : 'var(--bg-overlay-md)', color: isScheduleChanged ? '#fff' : 'var(--text-3)' }}",
  '          >',
  "            {isScheduleSaving ? <RefreshCw style={{ width: 14, height: 14, animation: 'spin 1s linear infinite' }} /> : '기본일정 저장'}",
  '          </button>',
  '        </div>',
];

lines.splice(262, 74, ...block);
fs.writeFileSync(path, lines.join('\n'), 'utf8');

