const fs = require('fs');

const path = 'src/components/tabs/ScheduleTab.js';
const lines = fs.readFileSync(path, 'utf8').split(/\r?\n/);

const block = [
  '        <div className="card" style={{ padding: \'16px\', gap: \'14px\' }}>',
  '          <div>',
  '            <h3 className="card-title">일자별 세부 조정</h3>',
  '            <p className="card-subtitle">직원을 먼저 선택해주세요.</p>',
  '          </div>',
  '',
  '          <div style={{ display: \'grid\', gap: \'8px\' }}>',
  '            <div className="leave-panel__summary-chip" style={{ justifyContent: \'space-between\' }}>',
  '              <span>선택 일자</span>',
  '              <strong>{selectedDateSummary}</strong>',
  '            </div>',
  '            <div className="leave-panel__summary-chip" style={{ justifyContent: \'space-between\' }}>',
  '              <span>현재 기본 시간</span>',
  '              <strong>{currentScheduleEnd ? `${currentSchedule} ~ ${currentScheduleEnd}` : currentSchedule}</strong>',
  '            </div>',
  '            <div className="leave-panel__summary-chip" style={{ justifyContent: \'space-between\' }}>',
  '              <span>등록된 조정</span>',
  '              <strong>{selectedOverrides.length}개</strong>',
  '            </div>',
  '          </div>',
  '',
  '          <form onSubmit={handleOverrideSubmit} style={{ display: \'grid\', gap: \'12px\' }}>',
  '            <div>',
  '              <div className="form-label">적용 일자</div>',
  '              <input',
  '                type="date"',
  '                className="form-input"',
  '                value={overrideDate}',
  '                onChange={(e) => {',
  '                  const nextDate = e.target.value;',
  '                  const nextOverride = overrideMap.get(nextDate);',
  '                  setOverrideDate(nextDate);',
  '                  setScheduleSelectedDates(nextDate ? [nextDate] : []);',
  '                  if (selectedEmp) {',
  '                    setOverrideTarget({ empNo: selectedEmp.empNo, name: selectedEmp.name });',
  '                  }',
  '                  setOverrideStart(String(nextOverride?.schedule_start || currentSchedule || \'08:00\').substring(0, 5));',
  '                  setOverrideEnd(String(nextOverride?.schedule_end || currentScheduleEnd || inferScheduleEndTime(nextOverride?.schedule_start || currentSchedule || \'08:00\', selectedEmp?.dept || \'\') || \'17:00\').substring(0, 5));',
  '                  setAllowOvertime(nextOverride ? Boolean(nextOverride.allow_overtime) : true);',
  '                  setOverrideNote(nextOverride?.note || \'\');',
  '                }}',
  '                disabled={!selectedEmp}',
  '                required',
  '              />',
  '            </div>',
  '',
  '            <div>',
  '              <div className="form-label">출근 기준 시각</div>',
  '              <select',
  '                className="ui-select"',
  '                value={overrideStart}',
  '                onChange={(e) => setOverrideStart(e.target.value)}',
  '                disabled={!selectedEmp || !overrideDate}',
  '                required',
  '                style={{ width: \'100%\' }}',
  '              >',
  '                {SCHEDULE_TIME_OPTIONS.map((time) => <option key={time} value={time}>{time}</option>)}',
  '              </select>',
  '            </div>',
  '',
  '            <label style={{',
  '              display: \'flex\',',
  '              alignItems: \'center\',',
  '              gap: \'8px\',',
  '              padding: \'10px 12px\',',
  '              borderRadius: \'12px\',',
  '              border: \'1px solid var(--border)\',',
  '              background: \'var(--bg-overlay-sm)\',',
  '              color: \'var(--text-1)\',',
  '              fontSize: \'13px\',',
  '              fontWeight: 600,',
  '            }}>',
  '              <input',
  '                type="checkbox"',
  '                checked={allowOvertime}',
  '                onChange={(e) => setAllowOvertime(e.target.checked)}',
  '                disabled={!selectedEmp || !overrideDate}',
  '                style={{ width: 16, height: 16, accentColor: \'var(--blue)\' }}',
  '              />',
  '              초과근무 허용',
  '            </label>',
  '',
  '            <div>',
  '              <div className="form-label">퇴근 기준 시각</div>',
  '              <select',
  '                className="ui-select"',
  '                value={overrideEnd}',
  '                onChange={(e) => setOverrideEnd(e.target.value)}',
  '                disabled={!selectedEmp || !overrideDate}',
  '                required',
  '                style={{ width: \'100%\' }}',
  '              >',
  '                {SCHEDULE_TIME_OPTIONS.map((time) => <option key={time} value={time}>{time}</option>)}',
  '              </select>',
  '            </div>',
  '',
  '            <div>',
  '              <div className="form-label">사유 / 메모</div>',
  '              <input',
  '                type="text"',
  '                className="form-input"',
  '                value={overrideNote}',
  '                onChange={(e) => setOverrideNote(e.target.value)}',
  '                placeholder="예: 교육 참석, 현장 조정, 조기 출근 조정"',
  '                disabled={!selectedEmp || !overrideDate}',
  '              />',
  '            </div>',
  '',
  '            <div style={{ display: \'flex\', gap: \'8px\', justifyContent: \'flex-end\', flexWrap: \'wrap\' }}>',
  '              {hasSelectedOverride && (',
  '                <button',
  '                  type="button"',
  '                  className="login-btn"',
  '                  onClick={() => handleDeleteOverride(selectedEmpNo)}',
  '                  style={{ marginTop: 0, background: \'rgba(208, 107, 107, 0.1)\', color: \'var(--red)\' }}',
  '                >',
  '                  삭제',
  '                </button>',
  '              )}',
  '              <button',
  '                type="button"',
  '                className="login-btn"',
  '                onClick={() => {',
  '                  setOverrideTarget(null);',
  '                  setOverrideDate(\'\');',
  '                  setScheduleSelectedDates([]);',
  '                  setOverrideStart(\'08:00\');',
  '                  setOverrideEnd(\'17:00\');',
  '                  setAllowOvertime(true);',
  '                  setOverrideNote(\'\');',
  '                }}',
  '                style={{ marginTop: 0 }}',
  '              >',
  '                선택 해제',
  '              </button>',
  '              <button',
  '                type="submit"',
  '                className="login-btn"',
  '                disabled={!selectedEmp || (scheduleSelectedDates.length === 0 && !overrideDate)}',
  '                style={{ marginTop: 0, background: \'var(--blue)\', color: \'#fff\' }}',
  '              >',
  "                {scheduleSelectedDates.length > 1 ? `${scheduleSelectedDates.length}개 날짜 조정 저장` : '조정 저장'}",
  '              </button>',
  '            </div>',
  '          </form>',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
];

lines.splice(422, lines.length - 422, ...block);
fs.writeFileSync(path, lines.join('\n'), 'utf8');

